<?php
$data = array (
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => '按种类分',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '5',
    'sort_order' => '11',
    'has_children' => '7',
    'goods_num' => 0,
    'level' => 0,
    'id' => '1',
    'name' => '按种类分',
  ),
  2 => 
  array (
    'cat_id' => '2',
    'cat_name' => '白酒',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 228,
    'level' => 1,
    'id' => '2',
    'name' => '白酒',
  ),
  3 => 
  array (
    'cat_id' => '3',
    'cat_name' => '红酒',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 115,
    'level' => 1,
    'id' => '3',
    'name' => '红酒',
  ),
  4 => 
  array (
    'cat_id' => '4',
    'cat_name' => '洋酒',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => '60',
    'level' => 1,
    'id' => '4',
    'name' => '洋酒',
  ),
  71 => 
  array (
    'cat_id' => '71',
    'cat_name' => '茶叶',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '71',
    'name' => '茶叶',
  ),
  72 => 
  array (
    'cat_id' => '72',
    'cat_name' => '茶具',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '72',
    'name' => '茶具',
  ),
  57 => 
  array (
    'cat_id' => '57',
    'cat_name' => '甜酒',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '57',
    'name' => '甜酒',
  ),
  73 => 
  array (
    'cat_id' => '73',
    'cat_name' => '酒具',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '73',
    'name' => '酒具',
  ),
  10 => 
  array (
    'cat_id' => '10',
    'cat_name' => '按产地分',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '12',
    'has_children' => '8',
    'goods_num' => '3',
    'level' => 0,
    'id' => '10',
    'name' => '按产地分',
  ),
  11 => 
  array (
    'cat_id' => '11',
    'cat_name' => '加拿大',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '11',
    'name' => '加拿大',
  ),
  12 => 
  array (
    'cat_id' => '12',
    'cat_name' => '法国',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 50,
    'level' => 1,
    'id' => '12',
    'name' => '法国',
  ),
  13 => 
  array (
    'cat_id' => '13',
    'cat_name' => '智利',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '13',
    'name' => '智利',
  ),
  15 => 
  array (
    'cat_id' => '15',
    'cat_name' => '意大利',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '15',
    'name' => '意大利',
  ),
  16 => 
  array (
    'cat_id' => '16',
    'cat_name' => '德国',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '16',
    'name' => '德国',
  ),
  20 => 
  array (
    'cat_id' => '20',
    'cat_name' => '美国',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '20',
    'name' => '美国',
  ),
  58 => 
  array (
    'cat_id' => '58',
    'cat_name' => '西班牙',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '58',
    'name' => '西班牙',
  ),
  59 => 
  array (
    'cat_id' => '59',
    'cat_name' => '澳洲',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '59',
    'name' => '澳洲',
  ),
  34 => 
  array (
    'cat_id' => '34',
    'cat_name' => '酒具大全',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '13',
    'has_children' => '6',
    'goods_num' => 43,
    'level' => 0,
    'id' => '34',
    'name' => '酒具大全',
  ),
  38 => 
  array (
    'cat_id' => '38',
    'cat_name' => '醒酒器',
    'measure_unit' => '',
    'parent_id' => '34',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '38',
    'name' => '醒酒器',
  ),
  35 => 
  array (
    'cat_id' => '35',
    'cat_name' => '开瓶器',
    'measure_unit' => '',
    'parent_id' => '34',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '35',
    'name' => '开瓶器',
  ),
  36 => 
  array (
    'cat_id' => '36',
    'cat_name' => '酒具礼品',
    'measure_unit' => '',
    'parent_id' => '34',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '36',
    'name' => '酒具礼品',
  ),
  37 => 
  array (
    'cat_id' => '37',
    'cat_name' => '酒架酒杯',
    'measure_unit' => '',
    'parent_id' => '34',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '37',
    'name' => '酒架酒杯',
  ),
  55 => 
  array (
    'cat_id' => '55',
    'cat_name' => '倒酒器',
    'measure_unit' => '',
    'parent_id' => '34',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '55',
    'name' => '倒酒器',
  ),
  54 => 
  array (
    'cat_id' => '54',
    'cat_name' => '保鲜瓶塞',
    'measure_unit' => '',
    'parent_id' => '34',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '54',
    'name' => '保鲜瓶塞',
  ),
  25 => 
  array (
    'cat_id' => '25',
    'cat_name' => '茶叶汇总',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '14',
    'has_children' => '7',
    'goods_num' => 0,
    'level' => 0,
    'id' => '25',
    'name' => '茶叶汇总',
  ),
  26 => 
  array (
    'cat_id' => '26',
    'cat_name' => '绿茶',
    'measure_unit' => '',
    'parent_id' => '25',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '26',
    'name' => '绿茶',
  ),
  27 => 
  array (
    'cat_id' => '27',
    'cat_name' => '普洱茶',
    'measure_unit' => '',
    'parent_id' => '25',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '27',
    'name' => '普洱茶',
  ),
  28 => 
  array (
    'cat_id' => '28',
    'cat_name' => '白茶',
    'measure_unit' => '',
    'parent_id' => '25',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '28',
    'name' => '白茶',
  ),
  30 => 
  array (
    'cat_id' => '30',
    'cat_name' => '红茶',
    'measure_unit' => '',
    'parent_id' => '25',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '30',
    'name' => '红茶',
  ),
  31 => 
  array (
    'cat_id' => '31',
    'cat_name' => '花茶',
    'measure_unit' => '',
    'parent_id' => '25',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '31',
    'name' => '花茶',
  ),
  32 => 
  array (
    'cat_id' => '32',
    'cat_name' => '黑茶',
    'measure_unit' => '',
    'parent_id' => '25',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '32',
    'name' => '黑茶',
  ),
  33 => 
  array (
    'cat_id' => '33',
    'cat_name' => '铁观音',
    'measure_unit' => '',
    'parent_id' => '25',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '8',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '33',
    'name' => '铁观音',
  ),
  40 => 
  array (
    'cat_id' => '40',
    'cat_name' => '茶具大全',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '15',
    'has_children' => '8',
    'goods_num' => '3',
    'level' => 0,
    'id' => '40',
    'name' => '茶具大全',
  ),
  41 => 
  array (
    'cat_id' => '41',
    'cat_name' => '陶瓷茶具',
    'measure_unit' => '',
    'parent_id' => '40',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '50',
    'level' => 1,
    'id' => '41',
    'name' => '陶瓷茶具',
  ),
  42 => 
  array (
    'cat_id' => '42',
    'cat_name' => '紫砂茶具',
    'measure_unit' => '',
    'parent_id' => '40',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '42',
    'name' => '紫砂茶具',
  ),
  43 => 
  array (
    'cat_id' => '43',
    'cat_name' => '茶具套装',
    'measure_unit' => '',
    'parent_id' => '40',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '43',
    'name' => '茶具套装',
  ),
  44 => 
  array (
    'cat_id' => '44',
    'cat_name' => '玻璃茶具',
    'measure_unit' => '',
    'parent_id' => '40',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '44',
    'name' => '玻璃茶具',
  ),
  45 => 
  array (
    'cat_id' => '45',
    'cat_name' => '功夫茶具',
    'measure_unit' => '',
    'parent_id' => '40',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '45',
    'name' => '功夫茶具',
  ),
  52 => 
  array (
    'cat_id' => '52',
    'cat_name' => '办公茶具',
    'measure_unit' => '',
    'parent_id' => '40',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '52',
    'name' => '办公茶具',
  ),
  47 => 
  array (
    'cat_id' => '47',
    'cat_name' => '旅行茶具',
    'measure_unit' => '',
    'parent_id' => '40',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '47',
    'name' => '旅行茶具',
  ),
  49 => 
  array (
    'cat_id' => '49',
    'cat_name' => '德化茶具',
    'measure_unit' => '',
    'parent_id' => '40',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '9',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '49',
    'name' => '德化茶具',
  ),
  68 => 
  array (
    'cat_id' => '68',
    'cat_name' => '收藏区',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 0,
    'id' => '68',
    'name' => '收藏区',
  ),
);
?>